Feature/automatically generate definitions
Riscure/python-trsfile pull request #25
Opened 2022-04-22 12:11 UTC by TomHogervorst

This PR addresses issues #23 , issue #24 and issue #15, and fixes the bug describes in issue #14 by creating a new trace set parameter map by default.

2022-04-25 08:52 UTC, Siebje requested changes
General comments:
- Props for writing comprehensive tests
- Please consider going over your code and adding type hints where possible (don't forget return types)
- Please reformat the files you touch. I noticed that some files are tab indented and some are space indented. Our standard uses spaces, so please correct the files you change.

2022-04-25 08:52 UTC, Siebje commented on trsfile/standardparameters.py
> +from enum import Enum
Please add a description to this file, as it may not be evident to a user what 'standard' means.

2022-04-25 08:52 UTC, Siebje commented on trsfile/parametermap.py
>      def __setitem__(self, key, value):
Since we're raising an error if the value is incorrectly typed, a type hint for the argument would be nice.

2022-04-25 08:52 UTC, Siebje commented on trsfile/parametermap.py
> +    def fill_from_headers(self, headers):
please type hint this as well (I'm guessing it's a dict of Header types?)

2022-04-25 08:52 UTC, Siebje commented on trsfile/parametermap.py
> +    def from_trace_parameter_map(trace_parameters):
type hints?

2022-04-25 08:52 UTC, Siebje commented on trsfile/engine/trs.py
> +		self.padding_mode = options.get('padding_mode', TracePadding.AUTO)
I'm not sure if this is the correct approach. If I understand it correctly, padding mode auto means that you would need to correct the length of already added traces if you encounter a longer trace added to the set. Since this is not supported by the TRS format, I would shy away from using 'padding mode' at all, or even deprecate it.

What you seem to be doing now is changing what the padding mode argument means, which I doubt is something you want to do.

2022-04-25 08:52 UTC, Siebje commented on trsfile/engine/trs.py
> +		self.padding_mode = options.get('padding_mode', TracePadding.AUTO)
After reading more of the code, it seems the use of the padding mode is slightly different than what I thought. The way it's used it maybe actually nice, so if this works, let's document it properly and leave it in.

the way I understand it to work now: If you pre-initialize the length of the trace and data (the full size of the contents of the definitions map), it will automatically pad any shorter entries. Keep in mind that padding a definitions map is not really possible though, and may have unexpected side effects.

2022-04-25 08:52 UTC, Siebje commented on trsfile/engine/trs.py
>  		# Finally add some extra headers that are freaking useful if they are not provided
maybe reword this to not say 'freaking' lol

2022-04-25 08:52 UTC, Siebje commented on trsfile/engine/trs.py
>  		# Write the headers to the file. WARNING: Do not call if the new headers have a different size than the
I would prefer the execution of the code to give this warning to the user rather than a comment in the code.

2022-04-25 13:29 UTC, TomHogervorst commented on trsfile/engine/trs.py
> +		self.padding_mode = options.get('padding_mode', TracePadding.AUTO)
You're right, I've removed the code that tries to pad an existing definitions map with data from a trace. It will only add a definition map with none exists yet.

2022-04-25 13:31 UTC, TomHogervorst commented on trsfile/engine/trs.py
>  		# Write the headers to the file. WARNING: Do not call if the new headers have a different size than the
I've move the check for this from the update_headers method to here.

2022-04-26 12:39 UTC, Siebje approved these changes

2022-04-26 12:39 UTC, merged