Feature/trace set parameters
Riscure/python-trsfile pull request #8
Opened 2021-06-01 16:01 UTC by johan-riscure

2021-06-07 14:03 UTC, Siebje requested changes

2021-06-08 14:11 UTC, johan-riscure commented on trsfile/parametermap.py
> +        name = raw.read(name_length).decode()
As discussed, yes, since it's the default, but changed now to be explicit

2021-06-08 14:11 UTC, johan-riscure commented on trsfile/parametermap.py
> +            out.extend(name.encode())
As discussed, yes, since it's the default, but changed now to be explicit

2021-06-08 14:12 UTC, johan-riscure commented on trsfile/traceparameter.py
> +        param_value = [int.from_bytes(io_bytes.read(ParameterType.INT.byte_size), 'little') for i in range(param_length)]
As discussed, it's equivalent, but updated to be consistent with the other statements

2021-06-08 14:12 UTC, johan-riscure commented on trsfile/utils.py
> +    return struct.pack('>h', value)
Fixed

2021-06-09 08:22 UTC, Siebje approved these changes

2021-06-09 14:39 UTC, merged