Feature/trace parameters
Riscure/python-trsfile pull request #9
Opened 2021-06-16 12:03 UTC by johan-riscure

2021-06-23 07:49 UTC, Siebje requested changes

2021-06-23 07:49 UTC, Siebje commented on trsfile/engine/trs.py
> +			traces.append(Trace(self.headers[Header.SAMPLE_CODING], samples, data, parameters, title, self.headers))
Why does it have a data _and_ a parameters field now? Shouldn't it be a replacement? Is this for backwards compatibility?

2021-06-23 07:49 UTC, Siebje commented on trsfile/trace.py
> +	def __init__(self, sample_coding, samples, data=b'', parameters=None, title='trace', headers={}):
So what happens now if the user supplies _both_ data _and_ parameters?

2021-06-23 07:49 UTC, Siebje commented on trsfile/traceparameter.py
> +        param_value = [struct.unpack('<d', io_bytes.read(ParameterType.DOUBLE.byte_size))[0] for i in range(param_length)]
I'm so confused by this statement. So you read Double.byte_size bytes, take only a single byte, and then skip to the next? What about the other 7 bytes? Are they implied because of the struct packing, and the address is figured out relatively? Or something?

2021-06-23 07:49 UTC, Siebje commented on trsfile/traceparameter.py
> +        param_value = bytes_read.decode()
Shouldn't you specify UTF-8 decoding here?

2021-06-23 07:49 UTC, Siebje commented on trsfile/traceparameter.py
>          encoded_string = self.value.encode()
And specify UTF-8 encoding here?

2021-06-23 08:07 UTC, johan-riscure commented on trsfile/traceparameter.py
> +        param_value = [struct.unpack('<d', io_bytes.read(ParameterType.DOUBLE.byte_size))[0] for i in range(param_length)]
No it's because struct.unpack returns a tuple, so I'm just turning it into a single value

2021-06-24 15:35 UTC, johan-riscure commented on trsfile/traceparameter.py
> +        param_value = bytes_read.decode()
Fixed

2021-06-24 15:36 UTC, johan-riscure commented on trsfile/traceparameter.py
>          encoded_string = self.value.encode()
Fixed

2021-06-24 15:37 UTC, johan-riscure commented on trsfile/trace.py
> +	def __init__(self, sample_coding, samples, data=b'', parameters=None, title='trace', headers={}):
That would be problematic indeed, I have removed the data part and made v1 trace sets behave like in the Java library (i.e. the trace data will be returned as a 'LEGACY_DATA' trace parameter)

2021-06-25 05:51 UTC, Siebje requested changes

2021-06-25 05:51 UTC, Siebje commented on trsfile/traceparameter.py
> +class TraceSetParameter:
Why did you make this change (no longer extending TraceParameter)?

2021-06-25 10:05 UTC, johan-riscure commented on trsfile/engine/file.py
> +			parameters['LEGACY_DATA'] = ByteArrayParameter(data)
That works, but to keep it consistent with the Java library I'll add a check the value must be non-zero length (except for strings)

2021-06-25 10:24 UTC, johan-riscure commented on trsfile/traceparameter.py
> +class TraceSetParameter:
That's actually the same as in the Java library. Because it's not necessary, this class basically only exists for the general deserialization of trace set parameters. I did not even include the serialization method as in the java code, because I think it would unnecessarily complicate the python code. (though I just realized that also means I can now remove empty method)

2021-06-25 13:18 UTC, Siebje approved these changes

2021-06-25 13:18 UTC, merged